name: doctor_on_demand
version: 1.1.4+18
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.4.0
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5
  firebase_messaging: ^14.2.2
  google_sign_in: ^5.3.3
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9
  google_fonts: ^5.1.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  string_validator: ^0.3.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.3.0
  date_picker_timeline: ^1.2.3
  flutter_stripe: ^10.1.1
  flutter_svg: ^2.0.10+1
  lottie: ^1.3.0
  http: ^1.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  package_info_plus: ^4.1.0
  file_picker: ^5.1.0
  uuid: ^3.0.6
  mime: ^1.0.2
  flutter_chat_ui:
    git:
      url: https://github.com/amsyary/flutter_chat_ui.git
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  jiffy: ^5.0.0
  agora_rtc_engine: ^5.3.1
  permission_handler: ^10.2.0
  flutter_callkit_incoming: ^1.0.3+3
  json_serializable: ^6.2.0
  json_annotation: ^4.8.0
  image_cropper: ^5.0.0
  sign_in_with_apple: ^5.0.0
  connectycube_flutter_call_kit: ^2.2.1
  get_storage: ^2.1.1
  table_calendar: ^3.0.8
  dropdown_search: ^5.0.6
  currency_text_input_formatter: ^2.1.8
  date_count_down: ^2.1.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.6
  flutter_native_splash: ^2.1.6
  patrol: ^3.3.0

dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/ic_launcher.png"
